# Pipeline: IDMAP Master Data Management (MDM) Product
# Source: ods__mdm.excel_mp_manual_data
# Action: Generate IDMAP for 1C and merge Ozon, WB, YM, Lemana, MVideo

connections:
  - sourceName: "ods_mdm"
    connection: "minioIceberg"
    configLocation: "configs/connections/yandex_s3_iceberg_ods_hadoop.yaml"

source:
  - sourceName: "ods_mdm"
    objectName: "mdm_product"
    initMode: "instantly"
    sourceFileSystem:
      tableName: "ods__mdm.excel_mp_manual_data"

transformations:
  - type: "idmap"
    sourceName: "mdm_product"
    connection: "ods_mdm"
    dataAtServer: false
    idMapGenerate:
      - alias: "gen_1c"
        systemCode: "1C"
        domainName: "product"
        timeColumn: "null"
        columnNames:
          - "kod_1s"

    idMapMerge:
      - alias: "merge_ozon"
        restoreRk: false
        in:
          systemCode: "1C"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_1s"]
        out:
          systemCode: "ozon"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_ozon"]

      - alias: "merge_wb"
        restoreRk: false
        in:
          systemCode: "1C"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_1s"]
        out:
          systemCode: "wb"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["artikul_wb_orion"]

      - alias: "merge_ym"
        restoreRk: false
        in:
          systemCode: "1C"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_1s"]
        out:
          systemCode: "yandex_market"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_yam"]

      - alias: "merge_lemana"
        restoreRk: false
        in:
          systemCode: "1C"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_1s"]
        out:
          systemCode: "lemana_pro"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_lemana_pro"]

      - alias: "merge_mvideo"
        restoreRk: false
        in:
          systemCode: "1C"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_1s"]
        out:
          systemCode: "mvideo"
          domainName: "product"
          timeColumn: "null"
          columnNames: ["kod_mvideo"]

target: []
