# Pipeline: STG -> ODS (Avro -> Iceberg)
# Source: s3://bi-dev/warehouse/stg__ozon.db/statistics_phrases/ (Avro)
# Target: s3://bi-dev/warehouse/ods__ozon.db/statistics_phrases/ (Iceberg)

connections:
- sourceName: stg_avro
  connection: minioAvro
  configLocation: configs/connections/local_stg_avro.yaml
- sourceName: ods_iceberg
  connection: minioIceberg
  configLocation: configs/connections/yandex_s3_iceberg_ods_hadoop.yaml
source:
- sourceName: stg_avro
  objectName: stg_statistics_phrases
  initMode: instantly
  sourceFileSystem:
    tableName: warehouse/stg__ozon.db/statistics_phrases
    partitionBy:
    - partition
    where: "partition = '${partition}'"
target:
- fileSystem:
    connection: ods_iceberg
    source: statistics_phrases_deduplicated
    tableName: ods__ozon.statistics_phrases
    targetFile: ods__ozon.db/statistics_phrases
    mode: mergeDelta
    mergeKeys:
    - campaignid
    - date
    - phrase
transformations:
- objectName: statistics_phrases_deduplicated
  deduplicate:
    sourceTable: stg_statistics_phrases
    uniqueKey:
    - campaignid
    - date
    - phrase
    deduplicationKey:
    - partition desc
