# Pipeline: STG -> ODS (Avro -> Iceberg)
# Source: s3://bi-dev/warehouse/stg__wb.db/report-detail/ (Avro)
# Target: s3://bi-dev/warehouse/ods__wb.db/report_detail/ (Iceberg, Hive Metastore)

connections:
- sourceName: stg_avro
  connection: minioAvro
  configLocation: configs/connections/local_stg_avro.yaml
- sourceName: ods_iceberg
  connection: minioIceberg
  configLocation: configs/connections/yandex_s3_iceberg_ods_hadoop.yaml
source:
- sourceName: stg_avro
  objectName: stg_report_detail
  initMode: instantly
  sourceFileSystem:
    tableName: warehouse/stg__wb.db/report-detail
target:
- fileSystem:
    connection: ods_iceberg
    source: report_detail_deduplicated
    tableName: ods__wb.report_detail
    targetFile: ods__wb.db/report_detail
    mode: mergeDelta
    mergeKeys:
    - rrdid
transformations:
- objectName: report_detail_deduplicated
  deduplicate:
    sourceTable: stg_report_detail
    uniqueKey:
    - rrdid
    deduplicationKey:
    - partition desc
    - rrdid desc
