# Pipeline to convert Ozon campaigns from Avro STG to Iceberg ODS
# Source: Yandex S3 s3://bi-dev/warehouse/stg__ozon.db/campaigns/ (Avro)
# Target: Yandex S3 s3://bi-dev/warehouse/ods__ozon.db/campaigns/ (Iceberg)

connections:
- sourceName: stg_avro
  connection: minioAvro
  configLocation: configs/connections/local_stg_avro.yaml
- sourceName: ods_iceberg
  connection: minioIceberg
  configLocation: configs/connections/yandex_s3_iceberg_ods_hadoop.yaml
source:
- sourceName: stg_avro
  objectName: stg_campaigns
  initMode: instantly
  sourceFileSystem:
    tableName: warehouse/stg__ozon.db/campaigns
target:
- fileSystem:
    connection: ods_iceberg
    source: campaigns_deduplicated
    tableName: ods__ozon.campaigns
    targetFile: ods__ozon.db/campaigns
    mode: mergeDelta
    mergeKeys:
    - id
transformations:
- objectName: campaigns_transformed
  sparkSql:
    sql: "SELECT \n  id,\n  title,\n  state,\n  advObjectType,\n  placement,\n  fromDate,\n\
      \  toDate,\n  dailyBudget,\n  budget,\n  weeklyBudget,\n  paymentType,\n  createdAt,\n\
      \  updatedAt,\n  CAST(partition as string) as partition\nFROM stg_campaigns\n"
- objectName: campaigns_deduplicated
  deduplicate:
    sourceTable: campaigns_transformed
    uniqueKey:
    - id
    deduplicationKey:
    - partition desc
    - updatedat desc
