# Pipeline: STG -> ODS (Avro -> Iceberg)
# Source: s3://bi-dev/warehouse/stg__ym.db/keywords/ (Avro)
# Target: s3://bi-dev/warehouse/ods__ym.db/keywords/ (Iceberg, Hive Metastore)

connections:
- sourceName: stg_avro
  connection: minioAvro
  configLocation: configs/connections/local_stg_avro.yaml
- sourceName: ods_iceberg
  connection: minioIceberg
  configLocation: configs/connections/yandex_s3_iceberg_ods_hadoop.yaml
source:
- sourceName: stg_avro
  objectName: stg_keywords
  initMode: instantly
  sourceFileSystem:
    tableName: warehouse/stg__ym.db/keywords
transformations:
- objectName: keywords_transformed
  sparkSql:
    sql: "SELECT \n  campaignId as campaignid,\n  orderId as orderid,\n  status,\n\
      \  substatus,\n  creationDate as creationdate,\n  offerId as offerid,\n  count,\n\
      \  price,\n  CAST(partition as string) as partition\nFROM stg_keywords\n"
- objectName: keywords_deduplicated
  deduplicate:
    sourceTable: keywords_transformed
    uniqueKey:
    - campaignid
    - orderid
    - offerid
    deduplicationKey:
    - partition desc
    - creationdate desc
target:
- fileSystem:
    connection: ods_iceberg
    source: keywords_deduplicated
    tableName: ods__ym.keywords
    targetFile: ods__ym.db/keywords
    mode: mergeDelta
    mergeKeys:
    - campaignid
    - orderid
    - offerid
