# Pipeline: STG -> ODS (JSON -> Iceberg)
# Source: s3://bi-dev/warehouse/stg__ozon.db/analytics_data/ (JSON)
# Target: s3://bi-dev/warehouse/ods__ozon.db/analytics_data/ (Iceberg)

connections:
- sourceName: stg_json
  connection: minioJson
  configLocation: configs/connections/local_stg_json.yaml
- sourceName: ods_iceberg
  connection: minioIceberg
  configLocation: configs/connections/yandex_s3_iceberg_ods_hadoop.yaml
source:
- sourceName: stg_json
  objectName: stg_analytics_data
  initMode: instantly
  sourceFileSystem:
    tableName: warehouse/stg__ozon.db/analytics_data
    partitionBy:
    - partition
    where: "partition = '${partition}'"
target:
- fileSystem:
    connection: ods_iceberg
    source: analytics_data_deduplicated
    tableName: ods__ozon.analytics_data
    targetFile: ods__ozon.db/analytics_data
    mode: mergeDelta
    mergeKeys:
    - sku
    - date
transformations:
- objectName: analytics_data_deduplicated
  deduplicate:
    sourceTable: stg_analytics_data
    uniqueKey:
    - sku
    - date
    deduplicationKey:
    - partition desc
