services:
  scala:
    image: datawiki/etl-tool:0.2
#    build:
#      context: .
    privileged: true
    container_name: scala
    volumes:
      - .:/source/
      - ./.sbt:/root/.sbt
      - ./.cache:/root/.cache
    #ports:
    #  - '22:22'