/usr/lib/jvm/jre-17/bin/java @/opt/etl-tool/dependency_v5 --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dlogback.configurationFile=file:/opt/etl-tool/logback.xml -Dfile.encoding=UTF-8 pro.datawiki.sparkLoader.sparkRun --config /opt/etl-tool/configMigrationManual/coldData.yaml --run_id scheduled__2025-10-07T11:50:00+00:00 --partition scheduled__2025-10-07T11:50:00+00:00 --load_date scheduled__2025-10-07T11:50:00+00:00 --debug false --external_progress_loging /opt/etl-tool/configMigrationOther/logger.yaml

/usr/lib/jvm/jre-17/bin/java @/opt/etl-tool/dependency_v5 --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dlogback.configurationFile=file:/opt/etl-tool/logback.xml -Dfile.encoding=UTF-8 pro.datawiki.sparkLoader.sparkRun --config /opt/etl-tool/configMigrationManual/coldData2.yaml --run_id scheduled__2025-10-07T11:50:00+00:00 --partition scheduled__2025-10-07T11:50:00+00:00 --load_date scheduled__2025-10-07T11:50:00+00:00 --debug false --external_progress_loging /opt/etl-tool/configMigrationOther/logger.yaml

/usr/lib/jvm/jre-17/bin/java @/opt/etl-tool/dependency_v5 --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dlogback.configurationFile=file:/opt/etl-tool/logback.xml -Dfile.encoding=UTF-8 pro.datawiki.sparkLoader.sparkRun --config /opt/etl-tool/configMigrationManual/coldDataCheck.yaml --run_id scheduled__2025-10-07T11:50:00+00:00 --partition scheduled__2025-10-07T11:50:00+00:00 --load_date scheduled__2025-10-07T11:50:00+00:00 --debug true --external_progress_loging /opt/etl-tool/configMigrationOther/logger.yaml

/usr/lib/jvm/jre-17/bin/java @/opt/etl-tool/dependency_v4 --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dlogback.configurationFile=file:/opt/etl-tool/logback.xml -Dfile.encoding=UTF-8 pro.datawiki.sparkLoader.sparkRun --config /opt/etl-tool/configMigrationManual/logger_events_traffic_source.yaml --run_id scheduled__2025-10-07T11:50:00+00:00 --partition scheduled__2025-10-07T11:50:00+00:00 --load_date scheduled__2025-10-07T11:50:00+00:00 --debug false --external_progress_loging /opt/etl-tool/configMigrationOther/logger.yaml

/usr/lib/jvm/jre-17/bin/java @/opt/etl-tool/dependency_v4 --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dlogback.configurationFile=file:/opt/etl-tool/logback.xml -Dfile.encoding=UTF-8 pro.datawiki.diMigration.main /opt/etl-tool/configMigration/attributeYaml.yaml


kubectl create secret generic trino-minio-credentials  --namespace dwh-sandbox  --from-literal=MINIO_ACCESS_KEY='C2IOmqOzVbYidtzcDySi'  --from-literal=MINIO_SECRET_KEY='AIqjtqnrSCJXn5Nyl7PDuRQStwyjsIrrutg2sTfR'


docker build -t datawiki/spark:0.0.2 .;docker push datawiki/spark:0.0.2