# Local S3 connection for reading Avro files from Yandex S3
minioHost:
  - hostUrl: null
    hostName: "nss1s3-enc.s3.ru"
    hostPort: 443

accessKey: "VXS717151INAVRCUAO02"
secretKey: "LzP7z4z3AW7vSfi09ukFmH69s_qO47_z723aA1Ar"
bucket: "bi-dev"
pathStyleAccess: true
establishTimeout: "15000"
connectionTimeout: "60000"
jsonMultiline: true
