package pro.datawiki.diMigration.core.task.coreTaskEtlToolTemplate.coreTaskEtlToolTemplateSource.coreTaskEtlToolTemplateSourceKafka

case class CoreTaskTemplateSourceKafkaTopic(topicList: List[String])