name: Deploy ETL-Tool

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x deploy-ci.sh

      - name: Deploy
        run: ./deploy-ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
